project:
  type: book
  output-dir: docs

book:
  title: "Clases de Econometría"
  author: "Juan Creide"
  chapters:
    - index.qmd
    - clase-20-3.qmd
    - clase-27-3.qmd
    - clase 31-3.qmd


format:
  html:
    toc: true
    lang: es
    theme:
      light: flatly
      dark: darkly
